[workspace]
authors = ["Anthony Tong <atong28.usa@gmail.com>"]
channels = ["conda-forge"]
name = "ScraperServer"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
streamlit = ">=1.49.1,<2"
markdown-it-py = ">=4.0.0,<5"
